changelog:
  exclude:
    labels:
      - 'dependencies'
      - 'documentation'
  categories:
    - title: '🚀 Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
        - 'fix'
        - 'bugfix'
        - 'bug'
    - title: '🧰 Maintenance'
      labels:
        - 'chore'
        - 'dependencies'
    - title: '📚 Documentation'
      labels:
        - 'documentation'
        - 'docs'
    - title: '🔒 Security'
      labels:
        - 'security'
        - 'fix'
        - 'bugfix'
        - 'bug'
  template: |
    ## What's Changed

    ${{#each releases}}
    ### {{name}}
    {{#if summary}}
    {{summary}}
    {{/if}}

    {{#if changes}}
    {{#each changes}}
    - {{#if scope}}**{{scope}}:** {{/if}}{{description}}
    {{/each}}
    {{/if}}
    {{#if breaking}}
    ### ⚠️ Breaking Changes
    {{#each breaking}}
    - {{#if scope}}**{{scope}}:** {{/if}}{{description}}
    {{/each}}
    {{/if}}
    {{#if issues}}
    ### 🐛 Bug Fixes
    {{#each issues}}
    - {{#if scope}}**{{scope}}:** {{/if}}{{description}}
    {{/each}}
    {{/if}}
    {{/each}}
