version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - ENVIRONMENT=development
      - PORT=8080
      - READ_TIMEOUT=10s
      - WRITE_TIMEOUT=10s
      - RATE_LIMIT=50
      - RATE_LIMIT_TIME=1m
      - LOG_LEVEL=debug
    volumes:
      - ./configs:/app/configs
    healthcheck:
      test:
        ['CMD', 'wget', '--spider', 'http://localhost:8080/v1/quotes/random']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
