basePath: /v1
definitions:
  repository.Quote:
    properties:
      author:
        type: string
      id:
        type: string
      tags:
        items:
          type: string
        type: array
      text:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: shawnmkost@gmail.com
    name: Shawn Kost
    url: https://github.com/shawnkost
  description: Public API for developer-related quotes
  title: Dev Quotes API
  version: "1.0"
paths:
  /quotes:
    get:
      description: Returns a list of quotes matching optional author and/or tag filters
      parameters:
      - description: Author name
        in: query
        name: author
        type: string
      - description: Tag name
        in: query
        name: tag
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/repository.Quote'
            type: array
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all quotes filtered by tag or author
      tags:
      - quotes
  /quotes/{id}:
    get:
      description: Retrieve a single quote by its unique ID
      parameters:
      - description: Quote ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repository.Quote'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get quote by ID
      tags:
      - quotes
  /quotes/random:
    get:
      description: Returns a single random quote from the dataset
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repository.Quote'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a random developer quote
      tags:
      - quotes
swagger: "2.0"
