name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            shawnkost/dev-quotes-api:latest
            shawnkost/dev-quotes-api:${{ github.sha }}

      - name: Deploy to Production
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          # Add your deployment commands here
          # Example for deploying to a cloud provider:
          # - aws ecs update-service --cluster your-cluster --service your-service --force-new-deployment
          # - or
          # - gcloud run deploy dev-quotes-api --image shawnkost/dev-quotes-api:${{ github.ref_name }}
